spring.application.name=backend-java
spring.application.name=backend-java

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_agent_db
spring.datasource.username=postgres
spring.datasource.password=yash2130

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=MySuperSecretKeyForAiSoftwareEngineeringAgent2026
jwt.expiration=86400000